name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          token: ${{ secrets.TOKEN }}
          base: header, activity
          plugin_languages: yes
          plugin_lines: yes
          plugin_languages_ignored: shell, csv
          plugin_languages_indepth: yes
          commits_authoring: Gijs Tempelman, gijstemp, 50988258+gijstemp@users.noreply.github.com, gijstempelman@gmail.com
          plugin_languages_categories: data, markup, programming
          plugin_habits: yes
          plugin_habits_charts: yes
